config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'

  root 'cards#index'
  
  resources :cards

  get 'signup'  => 'users#new'
  post 'signup' => 'users#create'
  resources :users

  get 'login'  => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'feed' => 'cards#feed'

  resources :decks
  resources :relationships, only: [:create, :destroy]
  resources :tags, only: [:show]

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :cards
  belongs_to :user
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :content, polymorphic: true
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :deck
  belongs_to :user

  validates :content, presence: true
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :content, styles: { small: "230x230>" }
  validates_attachment_content_type :content, :content_type => /\Aimage\/.*\Z/

  def from_url(url)
    content = URI.parse(url)
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  def snippet
    content.split[0..30].join(" ").strip
  end
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :followed, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :cards, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :card
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
  has_many :cards

  has_many :active_relationships, class_name: "Relationship", foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  def loose_cards
    cards.select{|c| c.deck.nil?}
  end

  def follow(user)
    following << user
  end

  def unfollow(user)
    following.destroy user
  end

  def following?(user)
    following.include? user
  end

  def feed
    Card.where("user_id IN (?)", following_ids)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  #layout "card_list", only: [:index, :feed]
  def index
    @cards = Card.all
  end

  def feed
    if logged?
      @cards = current_user.feed
      render "index"
    else
      redirect_to login_path
    end
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def show
    @deck = Deck.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
%header
  %h1.logo
    %a{href: logged? ? feed_path : root_path} Shuffler
  %nav
    - unless logged?
      = link_to "Register", signup_path
      |
      = link_to "Log in", login_path
      |
      three
    - else
      = current_user.email
      = link_to "Log out", logout_path

%div.top_links
  .sections
    = link_to "Feed", feed_path
    |
    = link_to "All", root_path
  .sorts
    New | Top
 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title Shuffler
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    = render 'layouts/header'
    .container
      .flash
        -flash.each do |name, msg|
          %div{class: name}= msg
      = yield